api/urls.py
from django.conf.urls import url
from django.shortcuts import HttpResponse
from api.views import person,other,video,img,article,user,html,file

def error(request):
    return HttpResponse('404')

urlpatterns = [
    url(r'^img/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', img.ImgApiView.as_view()),
    url(r'^gitc/img-(?P<library_id>\d+)/list.json$', img.get_img_list),
    url(r'^gitc/page/img-(?P<page_id>\d+)/list.json$', img.get_page_img_list),

    url(r'^video/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', video.VideoApiView.as_view()),

    url(r'^article/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', article.ArticleApiView.as_view()),
    url(r'^gitc/article-(?P<library_id>\d+)/list.json$', article.getarticlelist),
    url(r'^gitc/article/(?P<cid>\d+).json$', article.getarticle),

    # url(r'^person/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', person.PersonApiView.as_view()),
    url(r'^gitc/person-(?P<library_id>\d+)/list.json$', person.personlist),
    url(r'^gitc/person-(?P<page_id>\d+)/all/list.json$', person.page_person),
    url(r'^gitc/person/(?P<pid>\d+).json$', person.person),

    url(r'^other/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', html.HtmlApiView.as_view()),

    url(r'^gitc/user/(?P<phone>\d+).json$', user.userlogin),
    url(r'^gitc/code/(?P<phone>\d+).json$', user.sendsms),
    # 用户收藏信息
    url(r'^gitc/collect/(?P<phone>\d+).json$', user.getmycollect),
    url(r'^gitc/collect/add/(?P<phone>\d+).json$', user.add_user_collect),
    url(r'^gitc/file/(?P<phone>\d+).json$', user.user_file_collect),
    # 用户票务
    url(r'^gitc/tricket/list/(?P<phone>\d+).json$', user.user_tricket_list),
    url(r'^gitc/tricket/(?P<phone>\d+).json$', user.user_tricket),

    # 下载列表
    url(r'^gitc/file-(?P<library_id>\d+)/list.json$', file.get_file_list),

    url(r'^gitc/file/add/(?P<phone>\d+).json$', user.add_user_file),
    # 用户
    url(r'^gitc/sponsor/add.json$', other.sponsor_add),
    url(r'^gitc/meetissue/add.json$', other.meetissue_add),
    url(r'^gitc/meetissue/upload.json$', other.meetissue_upload),
    url(r'^contact/add.html$', other.ContactApiView),
    url(r'^member/logout.html$', user.user_logout),
    # url(r'^imguplod/(?P<page_id>\d+)/uplod.html$', views.imgup),
    #url(r'^update.html$', other.makedata),
    url(r'',error ),
]

gitc/urls.py
from django.conf.urls import url
from gitc.views import basics,logic,imgview,personview,articleview,htmlview,videoview,fileview,infoview,ticket,bill

urlpatterns = [
    url(r'^index.html$', basics.indexview),
    url(r'^login.html$', basics.loginview),
    url(r'^logout.html$', basics.logoutview),
    url(r'^changepwd.html$', basics.changepwd),
    url(r'^domain/index.html$', logic.DomainView.as_view()),

    url(r'^library/index.html$', logic.LibraryView.as_view()),
    url(r'^library/del/(?P<cid>\d+)$', logic.LibraryDel.as_view()),

    url(r'^page/index.html$', logic.PageView.as_view()),
    url(r'^page/del/(?P<cid>\d+)$', logic.PageDel.as_view()),

    url(r'^template/index.html$', logic.TemplateView.as_view()),
    url(r'^template/del/(?P<cid>\d+)$', logic.TemplateDel),
    # 加入我们
    url(r'^contact.html$', infoview.contact),
    url(r'^sponsor.html$', infoview.sponsorlist),
    url(r'^sponsor/del/(?P<cid>\d+)$', infoview.delsponsor),
    url(r'^sponsor/excel/(?P<bid>\d+)$', infoview.make_excel_sponsor),

    url(r'^memberlist.html$', infoview.menmberlist),
    url(r'^member/del/(?P<cid>\d+)$', infoview.delmenber),
    url(r'^member/edit/(?P<cid>\d+)$', infoview.MemberEdita.as_view()),
    url(r'^member/excel/(?P<bid>\d+)$', infoview.make_excel_menber),

    url(r'^meetissue.html$', infoview.meetissuelist),
    url(r'^meetissue/del/(?P<cid>\d+)$', infoview.delmeetissue),
    url(r'^meetissue/excel/(?P<bid>\d+)$', infoview.make_excel_meetissue),

    url(r'^bill.html$', bill.BillView.as_view()),
    url(r'^bill/(?P<cid>\d+)/edit.html$', bill.BillEdit.as_view()),
    url(r'^bill/del/(?P<bid>\d+)$', bill.del_bill),
    url(r'^bill/excel/(?P<bid>\d+)$', bill.make_excel_bill),
    url(r'^bill/(?P<domain_id>\d+)/upload.html$', bill.BillUpXls.as_view()),
    url(r'^bill/add.html$', bill.BillAdd.as_view()),
    url(r'^u/del/(?P<cid>\d+)$', basics.delcontact),

    url(r'^page/add.html$', logic.Addpage.as_view()),

    url(r'^page/(?P<cid>\d+)/index.html$', logic.UPageView.as_view()),

    url(r'^img-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', imgview.ImgView.as_view()),
    url(r'^img/(?P<page_id>\d+)/del/(?P<cid>\d+)$', imgview.ImgDel.as_view()),
    url(r'^article-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', articleview.ArticleView.as_view()),
    url(r'^article/(?P<page_id>\d+)/del/(?P<cid>\d+)$', articleview.ArticleDel.as_view()),
    url(r'^personnel-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', personview.PersonnelView.as_view()),
    url(r'^personnel/(?P<page_id>\d+)/del/(?P<cid>\d+)$', personview.PersonnelDel.as_view()),
    url(r'^personnel-(?P<page_id>\d+)/(?P<library_id>\d+)/import.html$', personview.ImportPerson.as_view()),
    url(r'^personnel/add/person$', personview.PersonAddAjax),
    url(r'^del/person/(?P<cid>\d+)$', personview.PersonDelAjax),

    url(r'^html-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', htmlview.HtmlView.as_view()),
    url(r'^html/(?P<page_id>\d+)/del/(?P<cid>\d+)$', htmlview.HtmlDel.as_view()),
    url(r'^video-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', videoview.VideoView.as_view()),
    url(r'^video/(?P<page_id>\d+)/del/(?P<cid>\d+)$', videoview.VideoDel.as_view()),
    url(r'^kindeditor/upload.html$', logic.upload_kindeditor_img),

    url(r'^eamil-type/index.html$', logic.MailTypeView.as_view()),
    url(r'^email/index.html$', logic.Mail.as_view()),

    url(r'^ticket/index.html$', ticket.TicketView.as_view()),
    url(r'^ticket/edit/index.html$', ticket.TicketEdit.as_view()),


    url(r'^file-(?P<page_id>\d+)/(?P<library_id>\d+)/add/0$', fileview.AddFileView.as_view()),
    url(r'^file-(?P<page_id>\d+)/(?P<library_id>\d+)/edit/(?P<cid>\d+)$', fileview.EditFileView.as_view()),
    # url(r'', basics.indexview),

]

webserver/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect
from webserver import settings
from webserver.views import page_not_found,permission_denied,page_error

def error(request):
    return redirect('http://www.thegitc.com')

def favicon(request):
    return redirect("/static/img/logo.png")


#handler403 = permission_denied
#handler404 = page_not_found
#handler500 = page_error

urlpatterns = [
    # url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve'),
    # url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^kingadmin/', admin.site.urls),
    url(r'^favicon.ico', favicon),
    url(r'^gitcadmin/', include('gitc.urls')),
    url(r'^api/', include('api.urls')),
    url(r'', error),
]

bmpdata/models.py
from django.db import models


# 主域名
class Domain(models.Model):
    name = models.CharField('域名名称', max_length=64)
    url = models.URLField('域名地址', max_length=128)
    imgpath = models.CharField('服务器图片路径', max_length=128, default="/data_new/", null=True, blank=True)
    token = models.CharField('token', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '1-域名管理'
        unique_together = ('name', 'url')


# 域名下模板表
class PageTemplate(models.Model):
    domain = models.ForeignKey('Domain')
    name = models.CharField('模板名称', max_length=64)
    img = models.CharField('分析图', max_length=255)

    def __str__(self):
        return '%s-%s' % (self.domain, self.name)

    class Meta:
        verbose_name_plural = '2-模板类型'
        unique_together = ('domain', 'name')


# 程序插件表
class Plugin(models.Model):
    name = models.CharField('插件名称', max_length=64)
    table = models.CharField('表名称', max_length=64, unique=True)

    def __str__(self):
        return '%s-%s' % (self.name, self.table)

    class Meta:
        verbose_name_plural = '3-插件库'


# 程序库表
class Library(models.Model):
    ptl = models.ForeignKey('PageTemplate')
    plugin = models.ForeignKey('Plugin')
    weight = models.SmallIntegerField('权重', default=1)
    name = models.CharField('库名称', max_length=64)
    other =  models.CharField('备注信息', max_length=256)
    width = models.CharField('宽度', max_length=10, default='100%', null=True, blank=True)
    height = models.CharField('高度', max_length=10, default='100%', null=True, blank=True)
    space = models.IntegerField('空间', default=10000000, null=True, blank=True)


    def __str__(self):
        return '%s-%s' % (self.ptl, self.name)

    class Meta:
        verbose_name_plural = '3-模板库'


class Page(models.Model):
    pp = models.ForeignKey('PageTemplate')
    name = models.CharField('页面名称', max_length=64)
    url = models.CharField('链接', max_length=256)

    def __str__(self):
        return '%s-%s' % (self.pp, self.name)

    class Meta:
        verbose_name_plural = '4-用户页面管理'
        unique_together = ('pp', 'name')


class Imgs(models.Model):
    ip = models.ForeignKey('Page')
    il = models.ForeignKey('Library')
    title = models.CharField('标题', max_length=64, null=True)
    content = models.TextField('文本', null=True)
    url = models.CharField('链接', max_length=256, null=True, blank=True)
    img = models.CharField('图片', max_length=255)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间", max_length=64, null=True, blank=True)

    def __str__(self):
        return '%s-%s' % (self.il, self.title)

    class Meta:
        verbose_name_plural = '5-图片信息'
        unique_together = ('ip', 'il', 'title')


class Video(models.Model):
    vp = models.ForeignKey('Page')
    vl = models.ForeignKey('Library')
    name = models.CharField('标题', max_length=64)
    url = models.CharField('视频地址', max_length=128)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间", max_length=64, null=True, blank=True)

    def __str__(self):
        return '%s-%s' % (self.vl, self.name)

    class Meta:
        verbose_name_plural = '5-视频信息'


class Article(models.Model):
    ap = models.ForeignKey('Page')
    al = models.ForeignKey('Library')
    name = models.CharField('文章名称', max_length=64)
    author = models.CharField('作者', max_length=20, null=True, blank=True, default='admin')
    img = models.CharField('缩略图', max_length=256, null=True)
    amount = models.IntegerField('访问量', default=1, null=True, blank=True)
    summary = models.CharField('简介', max_length=255, null=True)
    content = models.TextField('文章内容')
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)
    weight = models.SmallIntegerField('权重', default=1)

    def __str__(self):
        return '%s-%s' % (self.al, self.name)

    class Meta:
        verbose_name_plural = '5-文章信息'


class Personnel(models.Model):
    ppl = models.ForeignKey('Page')
    pl = models.ForeignKey('Library')
    name = models.CharField('姓名', max_length=64)
    ename = models.CharField('姓名拼音', max_length=128, null=True)
    company = models.CharField('公司名称', max_length=128, null=True)
    position = models.CharField('职位', max_length=128, null=True)
    pic = models.CharField('头像', max_length=256, null=True)
    summary = models.TextField('个人简介', null=True)
    stheme = models.CharField("演讲主题", max_length=255, null=True)
    sintroduce = models.TextField("演讲介绍", null=True)
    sdata = models.CharField("演讲日期", max_length=64, null=True)
    stime = models.CharField("演讲时间", max_length=64, null=True)
    meet = models.CharField("专场名称", max_length=128, null=True)
    meetaddr = models.CharField("会场地点", max_length=255, null=True)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    def __str__(self):
        return '%s-%s' % (self.pl, self.name)

    class Meta:
        verbose_name_plural = '5-人员信息'


class Html(models.Model):
    hp = models.ForeignKey('Page')
    hl = models.ForeignKey('Library')
    name = models.CharField('名称', max_length=64)
    html = models.TextField('代码')
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    def __str__(self):
        return '%s-%s' % (self.hp, self.name)

    class Meta:
        verbose_name_plural = '6-自定义字段'


class Files(models.Model):
    fp = models.ForeignKey('Page')
    fl = models.ForeignKey('Library')
    user = models.ForeignKey('Personnel', null=True, blank=True)
    name = models.CharField('文件名', max_length=64)
    url = models.CharField('链接地址', max_length=255)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    class Meta:
        unique_together = ('fp', 'fl', 'name')
        verbose_name = "文件下载管理"

    def __str__(self):
        return '%s-%s' % (self.fp, self.name)


class Contact(models.Model):
    name = models.CharField('姓名', max_length=32)
    email = models.EmailField('邮箱', unique=True)
    phone = models.CharField('手机', max_length=11, unique=True)
    company = models.CharField('公司', max_length=128, null=True)
    department = models.CharField('部门', max_length=64, null=True)
    position = models.CharField('职位', max_length=64, null=True)
    interest = models.CharField('兴趣', max_length=256, null=True)
    suggest = models.TextField('意见', null=True)
    creat_at = models.DateTimeField('创建时间', auto_now_add=True)
    weight = models.SmallIntegerField('权重', default=1)

    class Meta:
        verbose_name_plural = '6-加入我们信息'
        unique_together = ('name', 'phone')

    def __str__(self):
        return '%s-%s' % (self.name, self.phone)


class SysLog(models.Model):
    log_type_c = ((1, 'Info'), (2, 'Debug'), (3, 'WARN'), (4, 'ERROR'))
    user = models.CharField('操作用户', max_length=64)
    log_type = models.SmallIntegerField('日志类型', choices=log_type_c)
    content = models.TextField('日志内容')
    creat_time = models.DateTimeField(auto_now=True)


class EmailGroup(models.Model):
    effect_c = ((0, '接收'), (1, '发送'))
    name = models.CharField('组名称', max_length=64)
    effect = models.SmallIntegerField('作用', default=0, choices=effect_c)


class Email(models.Model):
    auth_c = ((0, '不认证'), (1, '认证'))
    ssh_c = ((0, '不加密'), (1, '加密'))

    eg = models.ForeignKey('EmailGroup')
    user = models.EmailField('邮件地址')
    passwd = models.CharField('密码', max_length=128, null=True)
    smtp = models.CharField('地址', max_length=128, null=True)
    port = models.IntegerField('端口', null=True)
    auth = models.SmallIntegerField('认证', choices=auth_c, null=True)
    issh = models.SmallIntegerField('加密', choices=ssh_c, null=True)


# 会员
class Memberinfo(models.Model):
    sex_chiose = ((1, "男"), (0, "女"))
    phone = models.CharField("手机号", max_length=11, unique=True)
    name = models.CharField("姓名", max_length=32, null=True, blank=True)
    sex = models.SmallIntegerField("性别",choices=sex_chiose,null=True, blank=True)
    age = models.SmallIntegerField("年龄", null=True, blank=True)
    email = models.EmailField("邮箱", null=True, blank=True)
    company = models.CharField("公司", max_length=256, null=True, blank=True)
    position = models.CharField("职位", max_length=256, null=True, blank=True)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    class Meta:
        verbose_name = "会员管理"

    def __str__(self):
        return '%s-%s' % (self.name, self.phone)


# 订单信息
class Bill(models.Model):
    sign_staus_chioes = ((0,"未签到"),(1,"已签到"))
    bd = models.ForeignKey("Domain")
    phone = models.CharField("手机号", max_length=11)
    code = models.CharField("签到码", max_length=64,null=True,blank=True)
    name = models.CharField("姓名", max_length=32, null=True, blank=True)
    order_time = models.CharField("订单时间", max_length=64,null=True,blank=True)
    order_nub = models.CharField("订单号", max_length=64,null=True,blank=True)
    bt = models.ForeignKey("Ticket")
    price = models.FloatField("门票价格",)
    channel = models.CharField("渠道",max_length=64,null=True,blank=True)
    channel_code = models.CharField("渠道编码",max_length=64,null=True,blank=True)
    sign_staus = models.SmallIntegerField("签到状态",choices=sign_staus_chioes,default=0)
    sign_time = models.CharField("签到时间",max_length=64,null=True,blank=True)
    remarks = models.CharField("备注",max_length=256,null=True,blank=True)
    ctime = models.CharField("创建时间",max_length=256,null=True,blank=True)

    class Meta:
        verbose_name = "订单信息"
        unique_together = ("order_nub","code","phone")

    def __str__(self):
        return '%s-%s' % (self.phone, self.order_nub)


# 我的收藏
class MemberPCollect(models.Model):
    mpc = models.ForeignKey("Memberinfo", verbose_name="用户")
    mp = models.ForeignKey("Personnel", verbose_name="嘉宾")

    class Meta:

templates/gitc/csrf.html
{% csrf_token %}

templates/gitc/index.html
{% extends 'base.html' %}
{% block title %}GITC{% endblock %}

{% block changpwd %}<a href="/gitcadmin/changepwd.html"> 修改密码</a>{% endblock %}

{% block caidan %}
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>GITC管理区</h3>
                <ul class="nav side-menu">
                  <li><a href="/gitcadmin/inde.html">
                      <i class="fa fa-home"></i>
                      后台主页</a>

                  </li>
                  <li><a><i class="fa fa-edit"></i> 页面管理 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/gitcadmin/page/add.html">添加页面</a></li>

                    </ul>
                  </li>
                    {% for foo in dm %}
                    <li><a><i class="fa fa-desktop"></i>{{ foo.name }}<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        {% for yh in foo.pagetemplate_set.all %}
                             <li><a href="/gitcadmin/domain/{{ yh.id }}/index.html">{{ yh.name }}</a></li>
                        {% endfor %}
                    </ul>
                  </li>
                    {% endfor %}
                  <li><a href="/gitcadmin/contact.html"><i class="fa fa-bar-chart-o"></i>加入我们</a>

                  </li>
                </ul>
              </div>
            </div>
{% endblock %}

{% block head %}
          <!-- 头部数据 -->
          <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top">
                  <i class="fa fa-user"></i>提交用户数</span>
              <div class="count">{{ yhs }}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 购票人数 </span>
              <div class="count">{{ goupiao }}</div>
              <span class="count_bottom"><i class="green">

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 收费总额</span>
              <div class="count green">{{ shoufei }}</div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 嘉宾数量 </span>
              <div class="count">{{ jiabin }}</div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 会议数量 </span>
              <div class="count">{{ meets }}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 图片数量合计 </span>
              <div class="count">{{ tp }}</div>
            </div>
          </div>
          <!-- 头部数据结束 -->
        {% endblock %}

{% block content %}
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>加入我们<small>月度数量对比</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      <iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
                      <canvas id="lineChart" width="761" height="380" style="width: 761px; height: 380px;"></canvas>
                  </div>
                </div>
              </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><font><font>馅饼面积图</font></font><small><font><font>会议</font></font></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content"><iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
                    <canvas id="polarArea" width="761" height="380" style="width: 761px; height: 380px;"></canvas>
                  </div>
                </div>
              </div>

          </div>

            {% endblock %}

templates/gitc/meetlist.html
{% extends 'gitc/index.html' %}
{% block title %}会议设置{% endblock %}

{% block head %}{% endblock %}

{% block content %}
<div class="row">
      <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>会议管理 <small></small></h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">搜索</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">

              <div class="clearfix"></div>

              <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>会议列表 <small></small></h2>
                      <div class="dt-buttons btn-group" style="margin-left: 30px;">
                            <button type="button" id="add" class="btn btn-success" data-toggle="modal" data-target="#myModal">添加会议</button>
                        </div>
                    <ul class="nav navbar-right panel_toolbox">
                      <li>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">

                    <div id="datatable-buttons_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline"
                               role="grid" aria-describedby="datatable-buttons_info" style="width: 50%;">
                              <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons"  style="width: 20px;">编号</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons"  style="width: 100px;">中文名称</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons"  style="width: 100px;">英文名称</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable-buttons"  style="width: 100px;">操作</th>
                                    </tr>
                              </thead>
                      <tbody>
                      {% for row in meet_list %}
                          <tr role="row" class="odd">
                              <td name="cid">{{ forloop.counter }}</td>
                              <td name="cname">{{ row.cname }}</td>
                              <td name="ename">{{ row.ename }}</td>
                              <td>
                                  <button type="button" class="btn btn btn-primary edit" cid="{{ row.id }}">编辑</button>
                                  <button type="button" class="btn btn-danger delhy" disabled="disabled" cid="{{ row.id }}">删除</button>
                              </td>
                            </tr>
                      {% endfor %}

                      </tbody>
                    </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">添加会议</h4>
      </div>
        <form action="" method="post">
            <div class="modal-body" style="height: 100px">
                {% csrf_token %}
                <input type="text" name="cid" id="id_cid_me" style="display: none">
                <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label" style="margin-top: 5px">会议中文名称</label>
                <div class="col-sm-8">
                  {{ obj.cname }}
                </div>
              </div>
                <div class="form-group">
                <label for="inputPassword3" class="col-sm-3 control-label" style="margin-top: 5px">会议英文名称</label>
                <div class="col-sm-8" style="margin-top: 5px">
                  {{ obj.ename }}
                </div>
              </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <input type="submit" class="btn btn-primary " value="保存"/>
            </div>
        </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



{% endblock %}

{% block js %}
    <script>
        $('.edit').click(function () {
            var cid = $(this).attr('cid');
            var cname = $(this).parent().prev().prev().text();
            var ename = $(this).parent().prev().text();
            $('#id_cname').val(cname);
            $('#id_ename').val(ename);
            $('#id_cid_me').val(cid);
            $('#myModal').modal('show');
        });
        $('#add').click(function () {
            $('#cid').val(0);
            $('#id_cname').val('');
            $('#id_ename').val('');
        })
    </script>
{% endblock %}