api/urls.py
from django.conf.urls import url
from django.shortcuts import HttpResponse
from api.views import person,other,video,img,article,user,html,file

def error(request):
    return HttpResponse('404')

urlpatterns = [
    url(r'^img/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', img.ImgApiView.as_view()),
    url(r'^gitc/img-(?P<library_id>\d+)/list.json$', img.get_img_list),
    url(r'^gitc/page/img-(?P<page_id>\d+)/list.json$', img.get_page_img_list),

    url(r'^video/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', video.VideoApiView.as_view()),

    url(r'^article/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', article.ArticleApiView.as_view()),
    url(r'^gitc/article-(?P<library_id>\d+)/list.json$', article.getarticlelist),
    url(r'^gitc/article/(?P<cid>\d+).json$', article.getarticle),

    # url(r'^person/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', person.PersonApiView.as_view()),
    url(r'^gitc/person-(?P<library_id>\d+)/list.json$', person.personlist),
    url(r'^gitc/person-(?P<page_id>\d+)/all/list.json$', person.page_person),
    url(r'^gitc/person/(?P<pid>\d+).json$', person.person),

    url(r'^other/(?P<doman_id>\d+)-(?P<page_id>\d+)-(?P<library_id>\d+).json$', html.HtmlApiView.as_view()),

    url(r'^gitc/user/(?P<phone>\d+).json$', user.userlogin),
    url(r'^gitc/code/(?P<phone>\d+).json$', user.sendsms),
    # 用户收藏信息
    url(r'^gitc/collect/(?P<phone>\d+).json$', user.getmycollect),
    url(r'^gitc/collect/add/(?P<phone>\d+).json$', user.add_user_collect),
    url(r'^gitc/file/(?P<phone>\d+).json$', user.user_file_collect),
    # 用户票务
    url(r'^gitc/tricket/list/(?P<phone>\d+).json$', user.user_tricket_list),
    url(r'^gitc/tricket/(?P<phone>\d+).json$', user.user_tricket),

    # 下载列表
    url(r'^gitc/file-(?P<library_id>\d+)/list.json$', file.get_file_list),

    url(r'^gitc/file/add/(?P<phone>\d+).json$', user.add_user_file),
    # 用户
    url(r'^gitc/sponsor/add.json$', other.sponsor_add),
    url(r'^gitc/meetissue/add.json$', other.meetissue_add),
    url(r'^gitc/meetissue/upload.json$', other.meetissue_upload),
    url(r'^contact/add.html$', other.ContactApiView),
    url(r'^member/logout.html$', user.user_logout),
    # url(r'^imguplod/(?P<page_id>\d+)/uplod.html$', views.imgup),
    #url(r'^update.html$', other.makedata),
    url(r'',error ),
]

webserver/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect
from webserver import settings
from webserver.views import page_not_found,permission_denied,page_error

def error(request):
    return redirect('http://www.thegitc.com')

def favicon(request):
    return redirect("/static/img/logo.png")


#handler403 = permission_denied
#handler404 = page_not_found
#handler500 = page_error

urlpatterns = [
    # url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve'),
    # url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^kingadmin/', admin.site.urls),
    url(r'^favicon.ico', favicon),
    url(r'^gitcadmin/', include('gitc.urls')),
    url(r'^api/', include('api.urls')),
    url(r'', error),
]

bmpdata/models.py
from django.db import models


# 主域名
class Domain(models.Model):
    name = models.CharField('域名名称', max_length=64)
    url = models.URLField('域名地址', max_length=128)
    imgpath = models.CharField('服务器图片路径', max_length=128, default="/data_new/", null=True, blank=True)
    token = models.CharField('token', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '1-域名管理'
        unique_together = ('name', 'url')


# 域名下模板表
class PageTemplate(models.Model):
    domain = models.ForeignKey('Domain')
    name = models.CharField('模板名称', max_length=64)
    img = models.CharField('分析图', max_length=255)

    def __str__(self):
        return '%s-%s' % (self.domain, self.name)

    class Meta:
        verbose_name_plural = '2-模板类型'
        unique_together = ('domain', 'name')


# 程序插件表
class Plugin(models.Model):
    name = models.CharField('插件名称', max_length=64)
    table = models.CharField('表名称', max_length=64, unique=True)

    def __str__(self):
        return '%s-%s' % (self.name, self.table)

    class Meta:
        verbose_name_plural = '3-插件库'


# 程序库表
class Library(models.Model):
    ptl = models.ForeignKey('PageTemplate')
    plugin = models.ForeignKey('Plugin')
    weight = models.SmallIntegerField('权重', default=1)
    name = models.CharField('库名称', max_length=64)
    other =  models.CharField('备注信息', max_length=256)
    width = models.CharField('宽度', max_length=10, default='100%', null=True, blank=True)
    height = models.CharField('高度', max_length=10, default='100%', null=True, blank=True)
    space = models.IntegerField('空间', default=10000000, null=True, blank=True)


    def __str__(self):
        return '%s-%s' % (self.ptl, self.name)

    class Meta:
        verbose_name_plural = '3-模板库'


class Page(models.Model):
    pp = models.ForeignKey('PageTemplate')
    name = models.CharField('页面名称', max_length=64)
    url = models.CharField('链接', max_length=256)

    def __str__(self):
        return '%s-%s' % (self.pp, self.name)

    class Meta:
        verbose_name_plural = '4-用户页面管理'
        unique_together = ('pp', 'name')


class Imgs(models.Model):
    ip = models.ForeignKey('Page')
    il = models.ForeignKey('Library')
    title = models.CharField('标题', max_length=64, null=True)
    content = models.TextField('文本', null=True)
    url = models.CharField('链接', max_length=256, null=True, blank=True)
    img = models.CharField('图片', max_length=255)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间", max_length=64, null=True, blank=True)

    def __str__(self):
        return '%s-%s' % (self.il, self.title)

    class Meta:
        verbose_name_plural = '5-图片信息'
        unique_together = ('ip', 'il', 'title')


class Video(models.Model):
    vp = models.ForeignKey('Page')
    vl = models.ForeignKey('Library')
    name = models.CharField('标题', max_length=64)
    url = models.CharField('视频地址', max_length=128)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间", max_length=64, null=True, blank=True)

    def __str__(self):
        return '%s-%s' % (self.vl, self.name)

    class Meta:
        verbose_name_plural = '5-视频信息'


class Article(models.Model):
    ap = models.ForeignKey('Page')
    al = models.ForeignKey('Library')
    name = models.CharField('文章名称', max_length=64)
    author = models.CharField('作者', max_length=20, null=True, blank=True, default='admin')
    img = models.CharField('缩略图', max_length=256, null=True)
    amount = models.IntegerField('访问量', default=1, null=True, blank=True)
    summary = models.CharField('简介', max_length=255, null=True)
    content = models.TextField('文章内容')
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)
    weight = models.SmallIntegerField('权重', default=1)

    def __str__(self):
        return '%s-%s' % (self.al, self.name)

    class Meta:
        verbose_name_plural = '5-文章信息'


class Personnel(models.Model):
    ppl = models.ForeignKey('Page')
    pl = models.ForeignKey('Library')
    name = models.CharField('姓名', max_length=64)
    ename = models.CharField('姓名拼音', max_length=128, null=True)
    company = models.CharField('公司名称', max_length=128, null=True)
    position = models.CharField('职位', max_length=128, null=True)
    pic = models.CharField('头像', max_length=256, null=True)
    summary = models.TextField('个人简介', null=True)
    stheme = models.CharField("演讲主题", max_length=255, null=True)
    sintroduce = models.TextField("演讲介绍", null=True)
    sdata = models.CharField("演讲日期", max_length=64, null=True)
    stime = models.CharField("演讲时间", max_length=64, null=True)
    meet = models.CharField("专场名称", max_length=128, null=True)
    meetaddr = models.CharField("会场地点", max_length=255, null=True)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    def __str__(self):
        return '%s-%s' % (self.pl, self.name)

    class Meta:
        verbose_name_plural = '5-人员信息'


class Html(models.Model):
    hp = models.ForeignKey('Page')
    hl = models.ForeignKey('Library')
    name = models.CharField('名称', max_length=64)
    html = models.TextField('代码')
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    def __str__(self):
        return '%s-%s' % (self.hp, self.name)

    class Meta:
        verbose_name_plural = '6-自定义字段'


class Files(models.Model):
    fp = models.ForeignKey('Page')
    fl = models.ForeignKey('Library')
    user = models.ForeignKey('Personnel', null=True, blank=True)
    name = models.CharField('文件名', max_length=64)
    url = models.CharField('链接地址', max_length=255)
    weight = models.SmallIntegerField('权重', default=1)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    class Meta:
        unique_together = ('fp', 'fl', 'name')
        verbose_name = "文件下载管理"

    def __str__(self):
        return '%s-%s' % (self.fp, self.name)


class Contact(models.Model):
    name = models.CharField('姓名', max_length=32)
    email = models.EmailField('邮箱', unique=True)
    phone = models.CharField('手机', max_length=11, unique=True)
    company = models.CharField('公司', max_length=128, null=True)
    department = models.CharField('部门', max_length=64, null=True)
    position = models.CharField('职位', max_length=64, null=True)
    interest = models.CharField('兴趣', max_length=256, null=True)
    suggest = models.TextField('意见', null=True)
    creat_at = models.DateTimeField('创建时间', auto_now_add=True)
    weight = models.SmallIntegerField('权重', default=1)

    class Meta:
        verbose_name_plural = '6-加入我们信息'
        unique_together = ('name', 'phone')

    def __str__(self):
        return '%s-%s' % (self.name, self.phone)


class SysLog(models.Model):
    log_type_c = ((1, 'Info'), (2, 'Debug'), (3, 'WARN'), (4, 'ERROR'))
    user = models.CharField('操作用户', max_length=64)
    log_type = models.SmallIntegerField('日志类型', choices=log_type_c)
    content = models.TextField('日志内容')
    creat_time = models.DateTimeField(auto_now=True)


class EmailGroup(models.Model):
    effect_c = ((0, '接收'), (1, '发送'))
    name = models.CharField('组名称', max_length=64)
    effect = models.SmallIntegerField('作用', default=0, choices=effect_c)


class Email(models.Model):
    auth_c = ((0, '不认证'), (1, '认证'))
    ssh_c = ((0, '不加密'), (1, '加密'))

    eg = models.ForeignKey('EmailGroup')
    user = models.EmailField('邮件地址')
    passwd = models.CharField('密码', max_length=128, null=True)
    smtp = models.CharField('地址', max_length=128, null=True)
    port = models.IntegerField('端口', null=True)
    auth = models.SmallIntegerField('认证', choices=auth_c, null=True)
    issh = models.SmallIntegerField('加密', choices=ssh_c, null=True)


# 会员
class Memberinfo(models.Model):
    sex_chiose = ((1, "男"), (0, "女"))
    phone = models.CharField("手机号", max_length=11, unique=True)
    name = models.CharField("姓名", max_length=32, null=True, blank=True)
    sex = models.SmallIntegerField("性别",choices=sex_chiose,null=True, blank=True)
    age = models.SmallIntegerField("年龄", null=True, blank=True)
    email = models.EmailField("邮箱", null=True, blank=True)
    company = models.CharField("公司", max_length=256, null=True, blank=True)
    position = models.CharField("职位", max_length=256, null=True, blank=True)
    ctime = models.CharField("创建时间",max_length=64,null=True,blank=True)

    class Meta:
        verbose_name = "会员管理"

    def __str__(self):
        return '%s-%s' % (self.name, self.phone)


# 订单信息
class Bill(models.Model):
    sign_staus_chioes = ((0,"未签到"),(1,"已签到"))
    bd = models.ForeignKey("Domain")
    phone = models.CharField("手机号", max_length=11)
    code = models.CharField("签到码", max_length=64,null=True,blank=True)
    name = models.CharField("姓名", max_length=32, null=True, blank=True)
    order_time = models.CharField("订单时间", max_length=64,null=True,blank=True)
    order_nub = models.CharField("订单号", max_length=64,null=True,blank=True)
    bt = models.ForeignKey("Ticket")
    price = models.FloatField("门票价格",)
    channel = models.CharField("渠道",max_length=64,null=True,blank=True)
    channel_code = models.CharField("渠道编码",max_length=64,null=True,blank=True)
    sign_staus = models.SmallIntegerField("签到状态",choices=sign_staus_chioes,default=0)
    sign_time = models.CharField("签到时间",max_length=64,null=True,blank=True)
    remarks = models.CharField("备注",max_length=256,null=True,blank=True)
    ctime = models.CharField("创建时间",max_length=256,null=True,blank=True)

    class Meta:
        verbose_name = "订单信息"
        unique_together = ("order_nub","code","phone")

    def __str__(self):
        return '%s-%s' % (self.phone, self.order_nub)


# 我的收藏
class MemberPCollect(models.Model):
    mpc = models.ForeignKey("Memberinfo", verbose_name="用户")
    mp = models.ForeignKey("Personnel", verbose_name="嘉宾")

    class Meta:

api/views/base.py
from bmpdata.models import Domain
from django.shortcuts import HttpResponse
import json
# 验证token


def datavalidate(func):
    def waper(req,*args,**kwargs):
        token = req.GET.get("token")
        if Domain.objects.filter(token=token).count() == 0:
            return HttpResponse(json.dumps({"status":False,"msg":"不合法的链接！"},ensure_ascii=False))
        ret = func(req,*args,**kwargs)
        return ret
    return waper

templates/changepwd.html
{% extends 'gitc/index.html' %}
{% block title %}修改密码{% endblock %}

{% block head %}{% endblock %}

{% block content %}
<div class="row">
      <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>修改密码 <small></small></h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">搜索</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">

              <div class="clearfix"></div>

              <div class="clearfix"></div>

              <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>修改密码 <small>{{ user }}</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                          <form class="form-horizontal" method="post">
                              {% if oldpassword_is_wrong %}
                                    <div class="alert alert-error">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <h4>错误!</h4>{{ errmsg }}
                                    </div>
                              {% endif %}

                              <div class="form-group">
                                <label for="inputEmail3" class="col-sm-2 control-label">原密码</label>
                                <div class="col-sm-10">
                                  {{ obj.oldpassword }}
                                </div>
                              </div>
                              <div class="form-group">{% csrf_token %}
                                <label for="inputPassword3" class="col-sm-2 control-label">新密码</label>
                                <div class="col-sm-10">
                                  {{ obj.newpassword1 }}
                                </div>
                              </div>
                              <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
                                <div class="col-sm-10">
                                  {{ obj.newpassword2 }}
                                </div>
                              </div>
                              <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                  <input type="submit" class="btn btn-success" value="确认修改">
                                </div>
                              </div>
                            </form>


                  </div>
                </div>
              </div>
            </div>
          </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load maketemplates %}
{% block title %}GITC{% endblock %}
{% block css %}
<style>
    .panel-qxxt{font-size: 16px;color: #0f0f0f;list-style:decimal;font-family:'Microsoft YaHei';font-style: normal;}
</style>
{% endblock %}

{% block changpwd %}<a href="/gitcadmin/changepwd.html"> 修改密码</a>{% endblock %}

{% block caidan %}
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/gitcadmin/index.html">
                      <i class="fa fa-home"></i>后台主页
                      </a>
                  </li>

                    {% for foo in domain_list %}
                            {% bt foo %}
                            <ul class="nav child_menu">
                                {% for yh in foo.pagetemplate_set.all %}
                                    {% for p in yh.page_set.all %}
                                        <li><a href="/gitcadmin/page/{{ p.id }}/index.html">{{ p.name }}</a></li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                          </li>
                    {% endfor %}
                <li><a href="/gitcadmin/page/add.html"><i class="fa fa-plus"></i>添加页面</a>
                <li><a><i class="fa fa-edit"></i> 信息中心 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                       <li><a href="/gitcadmin/contact.html"><i class="fa fa-university"></i>加入我们</a></li>
                        <li><a href="/gitcadmin/sponsor.html"><i class="fa fa-thumbs-o-up"></i>赞助列表</a></li>
                        <li><a href="/gitcadmin/meetissue.html"><i class="fa fa-book"></i>议题列表</a></li>
                        <li><a href="/gitcadmin/memberlist.html"><i class="fa fa-user"></i>会员管理</a></li>
                        <li><a href="/gitcadmin/bill.html"><i class="fa fa-barcode"></i>票务信息</a></li>
                    </ul>
                  </li>
                   <!--<li><a><i class="fa fa-edit"></i> 邮件设置 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/gitcadmin/eamil-type/index.html">1.邮件组</a></li>
                      <li><a href="/gitcadmin/email/index.html">2.邮件账户</a></li>

                    </ul>
                  </li>
                  -->
                  <li><a><i class="fa fa-edit"></i> 系统设置 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/gitcadmin/domain/index.html">1.网站设置</a></li>
                      <li><a href="/gitcadmin/template/index.html">2.模板设置</a></li>
                      <li><a href="/gitcadmin/library/index.html">3.插件管理</a></li>
                      <li><a href="/gitcadmin/page/index.html">4.页面管理</a></li>
                      <li><a href="/gitcadmin/file/index.html">5.文件管理</a></li>
                      <li><a href="/gitcadmin/ticket/index.html">6.票务管理</a></li>
                    </ul>
                  </li>
                  </li>
                </ul>
              </div>
            </div>
{% endblock %}

{% block head %}
          <!-- 头部数据 -->
          <div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top">
                  <i class="fa fa-user"></i> 提交用户数</span>
              <div class="count">{{ yhs }}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 购票人数 </span>
              <div class="count">{{ goupiao }}</div>
              <span class="count_bottom"><i class="green">

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 收费总额</span>
              <div class="count green">{{ shoufei }}</div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 嘉宾数量 </span>
              <div class="count">{{ jiabin }}</div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 页面数量 </span>
              <div class="count">{{ page }}</div>

            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> 图片数量合计 </span>
              <div class="count">{{ tp }}</div>
            </div>
          </div>
          <!-- 头部数据结束 -->
        {% endblock %}

{% block content %}
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h2 style="font-style:normal ">后台使用说明</h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="panel-body">
                        <div>
                        <ul class="panel-qxxt">
                            {% for a in web %}
                                <li>{{ a }}</li>
                            {% endfor %}
                        </ul>
                    </div>

                  </div>
                </div>
              </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h2 style="font-style:normal ">接口使用说明书</h2>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="panel-body">
                    <div>
                        <ul class="panel-qxxt">
                            {% for a in api %}
                                <li>{{ a }}</li>
                            {% endfor %}
                        </ul>
                    </div>

                  </div>
                </div>
              </div>

          </div>

            {% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ title }} </title>
    <!-- Bootstrap -->
    <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/static/vendors/animate.css/animate.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/static/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form method="post">
              <h1>{{ title }}</h1>
              <div>
                <input type="text" class="form-control" name="username" placeholder="账户" required="" />
              </div>
              <div>
                <input type="password" class="form-control" name="password" placeholder="密码" required="" />
                  {% csrf_token %}
              </div>
              <div>
                <input class="btn btn-success" style="width: 350px;margin-left: auto" type="submit" value="登录">
                  <div style="color: red">{{ error }}</div>
              </div>

              <div class="clearfix"></div>

              <div class="separator">

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><img src="/static/img/logo.png" alt="麒麟会"></h1>
                  <p>©2017 All Rights Reserved. </p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  </body>
</html>

templates/page_403.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>403 </title>

    <!-- Bootstrap -->
    <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
              <h1 class="error-number">403</h1>
              <h2>不知为了什么？</h2>
              <p>我竟然拒绝了你！ <a href="http://www.thegitc.com/index.html">官网</a>
              </p>
              <div class="mid_center">
                <a href="javascript:history.go(-1);" type="button" class="btn btn-success">后退</a>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/static/vendors/nprogress/nprogress.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/static/build/js/custom.min.js"></script>
  </body>
</html>

templates/page_404.html
{% extends 'index.html' %}

{% block head %}{% endblock %}

{% block content %}
<div class="panel panel-danger" style="margin-top: 65px;height: 100%;">
  <div class="panel-body text-center">
    <span style="font-size: 300px;vertical-align: middle;text-align: center;">404</span>
  </div>
</div>

{% endblock %}

{% block footer %}{% endblock %}